export {default as Home} from "./home/Home"
export {default as ProductView} from "./productView/ProductView"
export {default as Login} from "./login/Login"
export {default as Cart} from "./cart/Cart"
export {default as Error} from "./error/Error"
export {default as Register} from "./register/Register"
export {default as Cheackout} from "./cheackout/Cheackout"